### ISSUE TITLE
Make unitests pass with 3.13

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#1831]
s3path and s3 storage plugin are back for fun with my first attempt of python 3.13.

Will take a PR making CI pass with 3.13.

Integreation test on works on 3.13 (only tested on my latest MacOS X M1 laptop):
```
2024-12-03 22:09:02,962 DEBUG: Closing Master's aiohttp ClientSession and waiting 0.1 seconds (master.py:102)
Bandersnatch PyPI CI finished successfully!
```

**Comment by cooperlees** [comment]
Tested unittests - It's all PureS3Path fun. s3path module claims 3.13 support for 3.13 for 0.6.0.

Error:
```
self = PureS3Path('/'), args = ('/',), new_parts = ['/']

    def __init__(self, *args):
        super().__init__(*args)
    
        new_parts = list(self.parts)
        for part in new_parts[1:]:
            if part == '..':
                index = new_parts.index(part)
                new_parts.pop(index - 1)
                new_parts.remove(part)
    
        self._raw_paths = new_parts
>       self._load_parts()
E       AttributeError: 'PureS3Path' object has no attribute '_load_parts'

.tox/py3/lib/python3.13/site-packages/s3path/current_version.py:73: AttributeError
```

Updated to 0.6.0 and we worked on 3.13! Commit pushed here: https://github.com/pypa/bandersnatch/commit/228183b86bfe38c63ee38be33955037abf52f5d8

Got a python warning to debug:
```
src/bandersnatch/tests/test_master.py::test_master_doesnt_raise_if_serial_equal
  /usr/lib64/python3.13/asyncio/base_events.py:745: RuntimeWarning: coroutine method 'aclose' of 'Master.get' was never awaited
    self._ready.clear()
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
```

**Comment by cooperlees** [comment]
Everything passes with 3.13 since https://github.com/pypa/bandersnatch/pull/1848
